#!/bin/sh

set -e

#host=$(env | grep _TCP_ADDR | cut -d = -f 2)
host=ldap
port=$(env | grep _TCP_PORT | cut -d = -f 2)

echo -n "waiting for TCP connection to $host:$port..."

while ! nc -z $host $port 2>/dev/null
do
  echo "waiting"
  sleep 1
done

echo 'ok'
